### ISSUE TITLE
Building with LLVM Clang and OpenMP fails on Ubuntu 24.04

### ISSUE THREAD

**Issue by mmuetzel** [ElmerCSC/elmerfem#486]
When trying to build with LLVM Clang 18.1.3 on Ubuntu 24.04, linking `ViewFactors` fails with the following error when EulerFEM is configured to build with OpenMP (`CC=clang CXX=clang++ cmake -DWITH_OpenMP=ON ..`:
```
/usr/bin/ld: view3d/libview3d.a(ViewFactors.c.o): undefined reference to symbol '__kmpc_dispatch_next_4@@VERSION'
/usr/bin/ld: /lib/x86_64-linux-gnu/libomp.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

I don't know what causes that error or how to resolve it.

Building works after having configured with `-DWITH_OpenMP=OFF` (the default if `WITH_OpenMP` isn't set manually).

Is that a known issue?

**Comment by tzwinger** [comment]
Did I get it wrong, but are you still using `gfortran` for the Fortran part of Elmer? Simply, it works for me using `clang` and `clang++`, but as soon as I replace `gfortran` with `flang`, I get into all sorts of troubles. For CSC it would be very interesting to get it working with the complete LLVM compiler suite, as LLVM is important for our supercomputer LUMI, which has AMD hardware.

**Comment by mmuetzel** [comment]
Yes, this is still with `gfortran`. I only used `clang` and `clang++` instead of `gcc` and `g++`.
The reason for that error might be that some dependencies (OpenBLAS?) were built with `libgomp` on Ubuntu. And linking different OpenMP implementations into the same application causes errors.

When it comes to using LLVM Flang: MSYS2 (Windows MinGW) has the CLANG64 environment that is based on a LLVM toolchain (`clang`, `clang++`, `flang`, `lld`, `libomp`, ...):
https://www.msys2.org/docs/environments/

I'd like to add some CI runners for MSYS2 (incl. a runner using their CLANG64 environment) once the CMake build rules are ready for Windows. That would hopefully cover at least parts of the build configuration on your supercomputer.

**Comment by ghostforest** [comment]
I got a similar error. The linker cant find openMP or something. I suggest you check here: https://github.com/ElmerCSC/elmerfem/issues/503#issuecomment-2248193190
I'm on mac but the issue might be the same. I did get it to compile after all. Linking openMP with clang is explicitly difficult it seems. I posted my cmake command and my shell configuration. You might need to change the links to the libraries to match the locations on your system. 
I think it should be a lot easier to compile this. As of now I spent probably 2 weeks to get different configurations on mac compiled simply of lack of documentations or a decent cmake.

**Comment by mmuetzel** [comment]
I can't find the issue (i.e, the error message) that you saw in #503. 
Maybe you are confusing openMPI with OpenMP? The symbol that is reported as an undefined reference in the error message here belongs to the LLVM implementation of OpenMP afaict. It's not related to MPI.
https://llvm.org/doxygen/classllvm_1_1OpenMPIRBuilder.html#a49dbf0af8f3e1314b3b60222651b6fc2

**Comment by ghostforest** [comment]
I had the same issue as you. I had to explicitly link the dylib. That is what chat gpt told me. Adding 
```
export PATH="/opt/homebrew/opt/open-mpi/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/open-mpi/lib $LDFLAGS"
export CPPFLAGS="-I/opt/homebrew/opt/open-mpi/include $CPPFLAGS"
export OMPI_CC=/opt/homebrew/opt/llvm/bin/clang
export OMPI_CXX=/opt/homebrew/opt/llvm/bin/clang++
export OMPI_FC=/usr/local/bin/gfortran
```
to my shell configuration file,
and adding:
```
      -DMPI_C_COMPILER=/opt/homebrew/opt/open-mpi/bin/mpicc \
      -DMPI_CXX_COMPILER=/opt/homebrew/opt/open-mpi/bin/mpicxx \
      -DMPI_Fortran_COMPILER=/opt/homebrew/opt/open-mpi/bin/mpifort \
      -DCMAKE_C_FLAGS="-fopenmp" \
      -DCMAKE_CXX_FLAGS="-fopenmp" \
      -DCMAKE_EXE_LINKER_FLAGS="-L/opt/homebrew/opt/libomp/lib -lomp" \
```
to the cmake command solved the issue for me. I cant tell you more.

ChatGPT:
`
The error you're encountering is a linker error, indicating that the linker (ld) cannot find a required symbol (__kmpc_dispatch_next_4@@VERSION) which is part of the OpenMP library (libomp). This usually happens because the linker hasn't been provided with the necessary library to resolve the OpenMP symbols.
`

**Comment by mmuetzel** [comment]
Do you mean to explicitly link with `-lomp`? I haven't tried that. But maybe that's needed additionally to `-fopenmp` in that specific configuration...

**Comment by ghostforest** [comment]
I mean that I had the same problem as you and that I asked chatgpt and it told me:
`The error you're encountering is a linker error, indicating that the linker (ld) cannot find a required symbol (__kmpc_dispatch_next_4@@VERSION) which is part of the OpenMP library (libomp). This usually happens because the linker hasn't been provided with the necessary library to resolve the OpenMP symbols.`

Id simply compare your cmake command to mine and add what is missing regarding OpenMP.
Id compare your shell configuration to the part of mine that I posted and Id add what is missing....
Shell config seems to be important on Mac at least. Even stating all the directories in the cmake command will make the compiler not find things if its not defined in your shell profile.
Ofc you have to change the links so they point to the corresponding directories on your system.
See the last post in https://github.com/ElmerCSC/elmerfem/issues/503. Its all there.

If you tried that and it still fails we can look further. But for now apply the information that has been given to you.

Short answer:
YES

**Comment by mmuetzel** [comment]
Mixing different OpenMP implementations is probably a bad idea. I took the opposite approach and linked to the GNU implementation of OpenMP instead of linking explicitly with `-lomp`.
Let's see how that will fare: https://github.com/ElmerCSC/elmerfem/pull/487

**Comment by mmuetzel** [comment]
It looks like configuring with `CC=clang CXX=clang++ cmake -DWITH_OpenMP=ON -DOpenMP_C_FLAGS=-fopenmp=libgomp -DOpenMP_CXX_FLAGS=-fopenmp=libgomp ..` resolves the issue at link time.

So, this was a user error on configuration.
