### ISSUE TITLE
Refactoring of fem/src/ViewUtils.F90/PlanarReduce needed to compile on RHEL v8 with Intel v20.0.0

### ISSUE THREAD

**Issue by lucas-ige** [ElmerCSC/elmerfem#881]
I have an additional fix to suggest to fix a compilation error on RHEL8 with Intel v20.0.0 (it is the last one, with this fix I can compile Elmer). As far as I understand, it is needed because of [a bug in the Intel compiler suite that occurs with function value assignments within nested BLOCKS](https://community.intel.com/t5/Intel-Fortran-Compiler/Nested-blocks-prohibit-function-assignment/m-p/1083522).

This situation occurs in routine `PlanarReduce` in `fem/src/ViewUtils.F90`, which is constructed as follows:

```Fortran
FUNCTION PlanarReduce

    ! A bit of code here

    BLOCK

        ! Most of the routine code here, with nested BLOCKs

    END BLOCK

    ! A tiny bit of code here

END FUNCTION
```

When compiling on RHEL8 with Intel v20.0.0, this leads to errors as follows:

```
.../fem/src/ViewUtils.F90(330): error #7816: Invalid assignment to function result of external procedure.   [MESHOUT]
              MeshOut % Elements(nn) % Type => GetElementType(303)
```

Possible solutions:
 - Wait until the rest of my project lets go of Intel -> this is going to happen at some point but not soon enough for me 🤷
 - Wait until Intel fixes the problem -> not viable for me (or maybe it is already fixed in later versions but I am stuck with a specific version for now).
 - Refactor PlanarReduce to remove nested BLOCKs by:
    * removing the top-level BLOCK
    * removing the inner BLOCKs

While I understand the value of BLOCKs to keep namespaces tidy, they are probably less warranted when they span most of the body of the routine, especially when variables are named differently (eg `i2`, `Used2`) inside the BLOCK to avoid conflicts with like-variables (`i`, `Used`) in parent code. In that light, I think the preferable option is to remove the top-level BLOCK.

I am about to submit a PR for this change. I refrained from further refactoring since I have no idea what this piece of code does. I did see some dynamic arrays that are allocated but that never seem to be deallocated (eg. Set, Used, Ref, Set2, Used2, DirVec2) 🤔

**Comment by lucas-ige** [comment]
This was fixed by [commit d0f6d6b6](https://github.com/ElmerCSC/elmerfem/commit/d0f6d6b64387a747f3d50d7874c53ca99c926974).
